### ISSUE TITLE
Create dashboard for viewing stale, hanging, and abandoned PRs

### ISSUE THREAD

**Issue by nchammas** [databricks/spark-pr-dashboard#1]
Definitions:
* _stale PR_: A PR that hasn't been updated by anyone in 30 days.
* _hanging PR_: A stale PR that was last updated by a non-reviewer.
* _abandoned PR_: A stale PR that was last updated by a reviewer.

As [discussed here](http://apache-spark-developers-list.1001551.n3.nabble.com/Handling-stale-PRs-td8015.html), it would be good to manage the number of stale PRs we have. 

Having a dashboard that makes it easy to review the various kinds of stale PRs we have would help us keep the number low. Reviewers would use this dashboard to easily find PRs that need updating or closing.

**Comment by ajbozarth** [comment]
I have a branch with a stale PR dash implemented on my fork, but I haven't addressed hanging or abandoned PRs yet. 

What is considered a reviewer in the above definitions? (committer, not a bot, not the submitter?)

**Comment by nchammas** [comment]
I think that's a good definition of a reviewer for starters.

**Comment by ajbozarth** [comment]
@nchammas which are you referring to as a good definition? Committer, not a bot, or not the submitter? Because filtering on bots is already in the code, and filtering the submitter is mostly trivial but filtering on the Spark committers list is not trivial (though it may still be straight forward, I haven't tried yet)

**Comment by nchammas** [comment]
Oh, I meant the combination of all 3 conditions. But actually, just having reviewer = committer accomplishes the goal here and is simpler.

There might be a file in the main Spark repo that tracks the GitHub usernames of all the committers. @srowen or @rxin, would you happen to know something about this?

If we had an up-to-date list that tracked this, the PR dashboard could use it to generate reports as described in this issue.

**Comment by srowen** [comment]
I don't think there is a list of committer github handles. There's a list of JIRA usernames somehow somewhere in the ASF infra. But for purposes here, I'd take anyone that's not the submitter as a reviewer. And not Jenkins / the ASF bot.
