### ISSUE TITLE
Updated column should include line comments

### ISSUE THREAD

**Issue by nchammas** [databricks/spark-pr-dashboard#43]
It looks like the updated column only tracks comments on the PR as a whole, and not line comments. We probably want to include both.

**Comment by JoshRosen** [comment]
This is based off of the `updated_at` value delivered from GitHub, which in principle should incorporate updates due to line comments on the PR itself.  I'm going to close this as "cannot reproduce" for now.

**Comment by JoshRosen** [comment]
Actually, this does look like a legit. problem and I have an idea of how to fix it, so I'm going to re-open.
