### ISSUE TITLE
Remove PRs that no longer exist

### ISSUE THREAD

**Issue by shivaram** [databricks/spark-pr-dashboard#72]
There are some PRs which no longer exist on github but are shown in the PR dashboard UI. A simple one is in the EC2 tab of the live site right now. It shows a link to https://github.com/apache/spark/pull/12690 for me but that link itself throws a 404.

**Comment by shivaram** [comment]
Here is a screenshot of what I see FWIW
<img width="1661" alt="screenshot 2016-06-15 15 48 52" src="https://cloud.githubusercontent.com/assets/143893/16100069/b36f8644-3310-11e6-9f53-7bfa7e573589.png">

**Comment by ajbozarth** [comment]
@JoshRosen from my look at the code there doesn't exist a check for if a pr was deleted, so any deleted prs would become zombies on the dash. Or is this hidden somewhere and missing some deleted prs?

**Comment by ajbozarth** [comment]
Also from a quick look, that specific PR seems unique in this zombie state

**Comment by JoshRosen** [comment]
Fixed by #73.
