### ISSUE TITLE
Multiple github projects

### ISSUE THREAD

**Issue by evaldasou** [databricks/spark-pr-dashboard#80]
Hey guys,

Is it possible to add multiple projects to the pr-dashboard?
Configuration looks limited here:

`# GitHub account and repository name, separated by a slash.
GITHUB_PROJECT='apache/spark'

**Comment by evaldasou** [comment]
`# GitHub account and repository name, separated by a slash.
GITHUB_PROJECT='apache/spark'`

**Comment by JoshRosen** [comment]
Nope, it's not. I don't plan to add support for this since it's out of scope for own needs and would add complexity to the internals.
